services:
  caddy-pknw1.co.uk:
    networks:
      - proxy
    image: pknw1/pknw1.co.uk:latest
    container_name: caddy-pknw1.co.uk
    hostname: caddy-pknw1.co.uk
    environment:
      - VIRTUAL_HOST=pknw1.co.uk,nav.pknw1.co.uk,www.pknw1.co.uk,engineering.pknw1.co.uk,mobile.engineering.pknw1.co.uk,notflix.pknw1.co.uk
      - VIRTUAL_PORT=80

networks:
  proxy:
    external: true
    name: proxy
